### ISSUE TITLE
Confusion on mkdocstrings path

### ISSUE THREAD

**Issue by ashleyhe16** [pawamoy/mkdocstrings#161]
Hi, I think there's some confusion for me on how to correctly set the path to display classes/methods within a python module. 
I believe I set it up as the example code had on the original mkdocstrings repo but please let me know where I could be going wrong. I also followed the setup instructions given on the mkdocstrings website.

- `mkdocstrings` version: [0.13.6] (conda environment)

My project folder structure is as follows:
``` 
docstring_example.
├── docs
│    └── index.md
├── src
│       ├──  mkdocstrings
│                 └── __init__.py
│                 └── sample.py
└──  mkdocs.yml
```
sample.py
```
class SomeClass:
    """
    comment
    """
```
and mkdocs.yml:
```
site_name: sample site

plugins:
  - search
  - mkdocstrings:
      default_handler: python

theme:
  name: "material"

nav:
  - Home: index.md
  - About: about.md
```
I'm getting the following error when I add `::: mkdocstrings.sample.SomeClass` to my index.md:
```AttributeError: module 'mkdocstrings' has no attribute 'sample'

ERROR   -  mkdocstrings.extension: Could not collect 'mkdocstrings.sample'
ERROR   -  Error reading page 'index.md': module 'mkdocstrings' has no attribute 'sample'
Traceback (most recent call last):
  File "c:\users\hea2\anaconda3\envs\mkdocs\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\hea2\anaconda3\envs\mkdocs\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\hea2\Anaconda3\envs\mkdocs\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
  File "c:\users\hea2\anaconda3\envs\mkdocs\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\hea2\anaconda3\envs\mkdocs\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\hea2\anaconda3\envs\mkdocs\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\hea2\anaconda3\envs\mkdocs\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\hea2\anaconda3\envs\mkdocs\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\hea2\anaconda3\envs\mkdocs\lib\site-packages\mkdocs\__main__.py", line 133, in serve_command
    serve.serve(
  File "c:\users\hea2\anaconda3\envs\mkdocs\lib\site-packages\mkdocs\commands\serve.py", line 141, in serve
    config = builder()
  File "c:\users\hea2\anaconda3\envs\mkdocs\lib\site-packages\mkdocs\commands\serve.py", line 136, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "c:\users\hea2\anaconda3\envs\mkdocs\lib\site-packages\mkdocs\commands\build.py", line 271, in build
    _populate_page(file.page, config, files, dirty)
  File "c:\users\hea2\anaconda3\envs\mkdocs\lib\site-packages\mkdocs\commands\build.py", line 171, in _populate_page
    page.render(config, files)
  File "c:\users\hea2\anaconda3\envs\mkdocs\lib\site-packages\mkdocs\structure\pages.py", line 175, in render
    self.content = md.convert(self.markdown)
  File "c:\users\hea2\anaconda3\envs\mkdocs\lib\site-packages\markdown\core.py", line 263, in convert
    root = self.parser.parseDocument(self.lines).getroot()
  File "c:\users\hea2\anaconda3\envs\mkdocs\lib\site-packages\markdown\blockparser.py", line 90, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "c:\users\hea2\anaconda3\envs\mkdocs\lib\site-packages\markdown\blockparser.py", line 105, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "c:\users\hea2\anaconda3\envs\mkdocs\lib\site-packages\markdown\blockparser.py", line 123, in parseBlocks
    if processor.run(parent, blocks) is not False:
  File "c:\users\hea2\anaconda3\envs\mkdocs\lib\site-packages\mkdocstrings\extension.py", line 155, in run
    xml_element = self.process_block(identifier, str(block))
  File "c:\users\hea2\anaconda3\envs\mkdocs\lib\site-packages\mkdocstrings\extension.py", line 194, in process_block
    data: Any = handler.collector.collect(identifier, selection)
  File "c:\users\hea2\anaconda3\envs\mkdocs\lib\site-packages\mkdocstrings\handlers\python.py", line 221, in collect
    raise CollectionError(error)
mkdocstrings.handlers.CollectionError: module 'mkdocstrings' has no attribute 'sample' 
```
and when I change the code in index.md to `::: sample.SomeClass`, I get this error:
```
mkdocstrings.handlers.CollectionError: Importing 'sample.SomeClass' failed, possible causes are:
- an exception happened while importing
- an element in the path does not exist
```

**Comment by pawamoy** [comment]
You should not name your package `mkdocstrings` in SRC, as it clashes with mkdocstrings itself. It it still does not work after you renamed it, make sure to read [Finding modules](https://pawamoy.github.io/mkdocstrings/handlers/python/#finding-modules)!

**Comment by ashleyhe16** [comment]
Thank you! I ended up adding the following according to Finding modules and it now works for me. 

```
handlers:
       python:
          setup_commands:
            - import sys
            - sys.path.append("src")
```

**Comment by ashleyhe16** [comment]
Actually, I'm also trying to document functions outside of classes and I keep getting `module 'module_name' has no attribute 'somename'`. How do I just document functions in a module?

**Comment by ashleyhe16** [comment]
The above error came from having some import errors/ not having the proper packages installed with pip.

**Comment by pawamoy** [comment]
Glad you found an explanation and a solution, and sorry for not answering earlier!

**Comment by npucino** [comment]
@pawamoy I m having the same issue, could you document a bit better which packages you were missing please??

**Comment by pawamoy** [comment]
I believe @ashleyhe16 was missing packages on which their project depended. Nothing to do with mkdocstrings, and probably not the same packages as the ones you depend on. When you import your packages modules outside of mkdocstrings, does it work, or do you have import errors?

**Comment by npucino** [comment]
Thx @pawamoy for the quick reply. I fixed my issue. My problem was the imports in my modules .py files. I commented out all of them and now mkdocstrings works brilliantly. I have to understand why the imports made failing mkdocstrings now but not related here. Thx for the info!
