### ISSUE TITLE
Python 3.7+: cannot import name 'GenericMeta' from 'typing' 

### ISSUE THREAD

**Issue by StephenBrown2** [pawamoy/mkdocstrings#2]
When attempting to run with mkdocstrings in a python 3.7 venv, I got the following traceback:

<details><summary>Traceback (most recent call last):</summary>

```
  File "/path/to/repo/.nox/docs/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/path/to/repo/.nox/docs/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/path/to/repo/.nox/docs/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/path/to/repo/.nox/docs/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/path/to/repo/.nox/docs/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/path/to/repo/.nox/docs/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/path/to/repo/.nox/docs/lib/python3.7/site-packages/mkdocs/__main__.py", line 162, in build_command
    site_dir=site_dir
  File "/path/to/repo/.nox/docs/lib/python3.7/site-packages/mkdocs/config/base.py", line 197, in load_config
    errors, warnings = cfg.validate()
  File "/path/to/repo/.nox/docs/lib/python3.7/site-packages/mkdocs/config/base.py", line 107, in validate
    run_failed, run_warnings = self._validate()
  File "/path/to/repo/.nox/docs/lib/python3.7/site-packages/mkdocs/config/base.py", line 62, in _validate
    self[key] = config_option.validate(value)
  File "/path/to/repo/.nox/docs/lib/python3.7/site-packages/mkdocs/config/config_options.py", line 132, in validate
    return self.run_validation(value)
  File "/path/to/repo/.nox/docs/lib/python3.7/site-packages/mkdocs/config/config_options.py", line 572, in run_validation
    plgins[item] = self.load_plugin(item, cfg)
  File "/path/to/repo/.nox/docs/lib/python3.7/site-packages/mkdocs/config/config_options.py", line 580, in load_plugin
    Plugin = self.installed_plugins[name].load()
  File "/path/to/repo/.nox/docs/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/path/to/repo/.nox/docs/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/path/to/repo/.nox/docs/lib/python3.7/site-packages/mkdocstrings/__init__.py", line 10, in <module>
    from .plugin import MkdocstringsPlugin
  File "/path/to/repo/.nox/docs/lib/python3.7/site-packages/mkdocstrings/plugin.py", line 6, in <module>
    from .documenter import Documenter
  File "/path/to/repo/.nox/docs/lib/python3.7/site-packages/mkdocstrings/documenter.py", line 12, in <module>
    from typing import Any, Callable, Dict, GenericMeta, List, Optional, Pattern, Tuple, Type, Union
ImportError: cannot import name 'GenericMeta' from 'typing' (/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/typing.py)
```

</details>

A quick Google tells me that [`GenericMeta` is no longer in Python 3.7](https://github.com/hsolbrig/PyShEx/issues/17#issuecomment-427557545), and a workaround is:

```py
try:
    from typing import GenericMeta  # python 3.6
except ImportError:
    # in 3.7, genericmeta doesn't exist but we don't need it
    class GenericMeta(type): pass
```

**Comment by pawamoy** [comment]
Thank you for the report and the workaround :slightly_smiling_face: 

I'll do the change tomorrow :slightly_smiling_face:

**Comment by pawamoy** [comment]
Done in febf2b9, thanks again
