### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by RDIL** [pawamoy/mkdocstrings#43]
Getting this:
```python
ERROR   -  Error reading page 'libraries/filehandlers/api.md': list index out of range 
Traceback (most recent call last):
  File "/workspace/.pip-modules/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/workspace/.pip-modules/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/workspace/.pip-modules/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/workspace/.pip-modules/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/workspace/.pip-modules/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/workspace/.pip-modules/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/workspace/.pip-modules/lib/python3.7/site-packages/mkdocs/__main__.py", line 134, in serve_command
    livereload=livereload
  File "/workspace/.pip-modules/lib/python3.7/site-packages/mkdocs/commands/serve.py", line 119, in serve
    config = builder()
  File "/workspace/.pip-modules/lib/python3.7/site-packages/mkdocs/commands/serve.py", line 114, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/workspace/.pip-modules/lib/python3.7/site-packages/mkdocs/commands/build.py", line 274, in build
    _populate_page(file.page, config, files, dirty)
  File "/workspace/.pip-modules/lib/python3.7/site-packages/mkdocs/commands/build.py", line 181, in _populate_page
    'page_content', page.content, page=page, config=config, files=files
  File "/workspace/.pip-modules/lib/python3.7/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "/workspace/.pip-modules/lib/python3.7/site-packages/mkdocstrings/plugin.py", line 138, in on_page_content
    modified_lines[i] = "\n".join(renderer.render(root_object, heading))
  File "/workspace/.pip-modules/lib/python3.7/site-packages/mkdocstrings/renderer.py", line 27, in render
    self.render_object(obj, heading_level, lines)
  File "/workspace/.pip-modules/lib/python3.7/site-packages/mkdocstrings/renderer.py", line 59, in render_object
    self.render_categories(obj, heading_level + 1, lines)
  File "/workspace/.pip-modules/lib/python3.7/site-packages/mkdocstrings/renderer.py", line 80, in render_categories
    self.render_object(method, heading_level + extra_level, lines)
  File "/workspace/.pip-modules/lib/python3.7/site-packages/mkdocstrings/renderer.py", line 50, in render_object
    lines.append(f'\n??? note "Show source code in {obj.relative_file_path}"')
  File "/workspace/.pip-modules/lib/python3.7/site-packages/mkdocstrings/documenter.py", line 190, in relative_file_path
    while path_parts[-1] != file_path_parts[-1]:
IndexError: list index out of range
```

**Comment by pawamoy** [comment]
Hello, this may have been fixed in latest version, could you try again with version 0.7.1?

**Comment by RDIL** [comment]
Nope, this is on Linux in Docker

**Comment by pawamoy** [comment]
OK thanks. What Linux distro (so I can try and replicate)?

**Comment by RDIL** [comment]
Ubuntu, and I haven't tried yet on latest

**Comment by RDIL** [comment]
Ok, tried on latest and it is still doing the same thing.
Here is the PR for reproduction: https://github.com/rdilweb/docs/pull/9

**Comment by pawamoy** [comment]
OK, I was able to replicate. The issue happens because while computing the relative path we are searching for the file name in the Python dotted path, which does not appear since it's in the `__init__.py` file. Not sure how I will fix it, but I will :slightly_smiling_face: 

Anyway that `relative_file_path` function is ugly, there's surely a more robust way to compute this.

**Comment by RDIL** [comment]
I suppose something like this could work if I'm not wrong:
```python
files = os.listdir(module_name)
if len(files) < 2:
    # only __init__
```
I just really need this fixed, because while its not my library has no documentation :(

**Comment by pawamoy** [comment]
Does it look good :slightly_smiling_face: ?

![Screenshot_2020-02-25_21-05-19](https://user-images.githubusercontent.com/3999221/75283016-47792a00-5812-11ea-8a02-2b2a709a0ba3.png)

Just pushed to master, could try with latest commit?

**Comment by RDIL** [comment]
That looks great, I will try in a second.
One minor thing:
It says
```Show source code in filehandlers/init.py```,
where it should say:
```Show source code in filehandlers/__init__.py```
Not sure why its happening but other than that, it looks great, thanks!!

**Comment by pawamoy** [comment]
Yes I saw it too, it's fixed as well in 2525f39ad8c181679fa33db8e6dfaa28eb39c289 :slightly_smiling_face:

**Comment by RDIL** [comment]
Alright, trying to clone so I can test it now 👍

**Comment by RDIL** [comment]
Oh no!! Getting this now:
```
ERROR   -  Error reading page 'libraries/filehandlers/api.md': string indices must be integers 
Traceback (most recent call last):
  File "/workspace/.pip-modules/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/workspace/.pip-modules/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/workspace/.pip-modules/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/workspace/.pip-modules/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/workspace/.pip-modules/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/workspace/.pip-modules/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/workspace/.pip-modules/lib/python3.7/site-packages/mkdocs/__main__.py", line 143, in serve_command
    **kwargs
  File "/workspace/.pip-modules/lib/python3.7/site-packages/mkdocs/commands/serve.py", line 141, in serve
    config = builder()
  File "/workspace/.pip-modules/lib/python3.7/site-packages/mkdocs/commands/serve.py", line 136, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/workspace/.pip-modules/lib/python3.7/site-packages/mkdocs/commands/build.py", line 274, in build
    _populate_page(file.page, config, files, dirty)
  File "/workspace/.pip-modules/lib/python3.7/site-packages/mkdocs/commands/build.py", line 178, in _populate_page
    'page_content', page.content, page=page, config=config, files=files
  File "/workspace/.pip-modules/lib/python3.7/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "/workspace/.pip-modules/lib/python3.7/site-packages/mkdocstrings/plugin.py", line 143, in on_page_content
    page.toc = get_toc(getattr(md, "toc", ""))
  File "/workspace/.pip-modules/lib/python3.7/site-packages/mkdocs/structure/toc.py", line 11, in get_toc
    toc = [_parse_toc_token(i) for i in toc_tokens]
  File "/workspace/.pip-modules/lib/python3.7/site-packages/mkdocs/structure/toc.py", line 11, in <listcomp>
    toc = [_parse_toc_token(i) for i in toc_tokens]
  File "/workspace/.pip-modules/lib/python3.7/site-packages/mkdocs/structure/toc.py", line 59, in _parse_toc_token
    anchor = AnchorLink(token['name'], token['id'], token['level'])
TypeError: string indices must be integers
```

**Comment by pawamoy** [comment]
Ah! You need to [pin mkdocs to version 1.0.4](https://github.com/mkdocs/mkdocs/issues/2002). I'll fix that asap :joy:

**Comment by RDIL** [comment]
Yes, it works on mkdocs 1.0.4 yayyy thank you 😍

**Comment by pawamoy** [comment]
Great, closing, expect v0.8 (compatible with mkdocs 1.1) to be released around this week-end.
