### ISSUE TITLE
AnchorLink TypeError

### ISSUE THREAD

**Issue by pawamoy** [pawamoy/mkdocstrings#47]
If you run into this error:

```
...
File "/path/to/venv/lib/python3.7/site-packages/mkdocs/structure/toc.py", line 59, in _parse_toc_token
    anchor = AnchorLink(token['name'], token['id'], token['level'])
TypeError: string indices must be integers
```

The solution is to temporarily pin your version of `mkdocs` to 1.0.4.

I will soon release version 0.8.0 that will be compatible with mkdocs 1.1 (but not compatible anymore with mkdocs < 1.1, unless someone can advise me on how to support both!).

**Comment by pawamoy** [comment]
I wonder: should I add `mkdocs >= 1.1` is the v0.8?

**Comment by StephenBrown2** [comment]
Yes

**Comment by HuiiBuh** [comment]
I would have said so

**Comment by pawamoy** [comment]
Just released version 0.8.0. Always a bit scared of releasing :fearful:, please tell me if there's issues with this version!

**Comment by koaning** [comment]
The original issue was fixed, but this introduces a new bug on my side. 

```
(venv) ➜  whatlies git:(github) ✗ mkdocs serve                                        
INFO    -  Building documentation... 
INFO    -  Cleaning site directory 
Traceback (most recent call last):
  File "/Users/vincent/Development/whatlies/venv/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/Users/vincent/Development/whatlies/venv/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/vincent/Development/whatlies/venv/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/vincent/Development/whatlies/venv/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/vincent/Development/whatlies/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/vincent/Development/whatlies/venv/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/vincent/Development/whatlies/venv/lib/python3.6/site-packages/mkdocs/__main__.py", line 143, in serve_command
    **kwargs
  File "/Users/vincent/Development/whatlies/venv/lib/python3.6/site-packages/mkdocs/commands/serve.py", line 141, in serve
    config = builder()
  File "/Users/vincent/Development/whatlies/venv/lib/python3.6/site-packages/mkdocs/commands/serve.py", line 136, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/Users/vincent/Development/whatlies/venv/lib/python3.6/site-packages/mkdocs/commands/build.py", line 288, in build
    _build_theme_template(template, env, files, config, nav)
  File "/Users/vincent/Development/whatlies/venv/lib/python3.6/site-packages/mkdocs/commands/build.py", line 114, in _build_theme_template
    output = _build_template(template_name, template, files, config, nav)
  File "/Users/vincent/Development/whatlies/venv/lib/python3.6/site-packages/mkdocs/commands/build.py", line 93, in _build_template
    output = template.render(context)
  File "/Users/vincent/Development/whatlies/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/vincent/Development/whatlies/venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/vincent/Development/whatlies/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/vincent/Development/whatlies/venv/lib/python3.6/site-packages/material/404.html", line 4, in top-level template code
    {% extends "base.html" %}
  File "/Users/vincent/Development/whatlies/venv/lib/python3.6/site-packages/material/base.html", line 108, in top-level template code
    {% block header %}
  File "/Users/vincent/Development/whatlies/venv/lib/python3.6/site-packages/material/base.html", line 109, in block "header"
    {% include "partials/header.html" %}
  File "/Users/vincent/Development/whatlies/venv/lib/python3.6/site-packages/material/partials/header.html", line 7, in top-level template code
    {% include "partials/logo.html" %}
  File "/Users/vincent/Development/whatlies/venv/lib/python3.6/site-packages/material/partials/logo.html", line 5, in top-level template code
    <img src="{{ config.theme.logo | url }}" alt="logo">
  File "/Users/vincent/Development/whatlies/venv/lib/python3.6/site-packages/mkdocs/utils/filters.py", line 14, in url_filter
    return normalize_url(value, page=context['page'], base=context['base_url'])
  File "/Users/vincent/Development/whatlies/venv/lib/python3.6/site-packages/mkdocs/utils/__init__.py", line 223, in normalize_url
    path = path_to_url(path or '.')
  File "/Users/vincent/Development/whatlies/venv/lib/python3.6/site-packages/mkdocs/utils/__init__.py", line 251, in path_to_url
    return '/'.join(path.split('\\'))
AttributeError: 'dict' object has no attribute 'split'
```

**Comment by pawamoy** [comment]
This seems to be a problem with `mkdocs` or `mkdocs-material` and not `mkdocstrings`.

Do you have a link to a repo on which I could try to reproduce and debug?

**Comment by koaning** [comment]
It was related to https://github.com/pawamoy/mkdocstrings/issues/85#issuecomment-613409534.
