### ISSUE TITLE
Module 'bot' not found.

### ISSUE THREAD

**Issue by dadyarri** [pawamoy/mkdocstrings#79]
Hello. Trying to use your plugin in my bot's documentation. And i can't understand, what folders i should watch. Here is my project's structure:
![Screenshot_20200409_140836](https://user-images.githubusercontent.com/51821039/78889113-bc738c80-7a6b-11ea-9093-4c5740b21b23.png)

Here is my mkdocstrings' config:
```yaml
    - mkdocstrings:
        default_handler: python
        handlers:
            python:
            rendering:
                show_source: true
    - watch:
        - bot
        - ../bot
```

Here is content of `.md` file:

`::: bot.keyboards`

And it produces this error:

```python
ERROR   -  mkdocstrings.handlers.python: Collection failed: No module named 'bot'
Traceback (most recent call last):
  File "/home/dadyarri/projects/bjorn/venv_bjorn/lib/python3.8/site-packages/pytkdocs/loader.py", line 133, in get_object_tree
    parent_module = importlib.import_module(parent_module_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'bot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dadyarri/projects/bjorn/venv_bjorn/lib/python3.8/site-packages/pytkdocs/cli.py", line 179, in main
    print(json.dumps(process_json(line)))
  File "/home/dadyarri/projects/bjorn/venv_bjorn/lib/python3.8/site-packages/pytkdocs/cli.py", line 116, in process_json
    return process_config(json.loads(json_input))
  File "/home/dadyarri/projects/bjorn/venv_bjorn/lib/python3.8/site-packages/pytkdocs/cli.py", line 93, in process_config
    obj = loader.get_object_documentation(path, members)
  File "/home/dadyarri/projects/bjorn/venv_bjorn/lib/python3.8/site-packages/pytkdocs/loader.py", line 205, in get_object_documentation
    leaf = get_object_tree(dotted_path)
  File "/home/dadyarri/projects/bjorn/venv_bjorn/lib/python3.8/site-packages/pytkdocs/loader.py", line 136, in get_object_tree
    raise ImportError("No module named '%s'" % obj_parent_modules[0])
ImportError: No module named 'bot'
 
ERROR   -  mkdocstrings.extension: Could not collect 'bot.keyboards' 

```

How can i import contain of `bot` module and root of the project?

**Comment by pawamoy** [comment]
First, the `watch` key must be in the `plugin.mkdocstrings` one:

```yaml
plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
        rendering:
          show_source: true
    watch:
      - bot
      - ../bot
```

Now, just so you know, the `watch` list has nothing to do with the collection of objects. It's a bonus for when you are serving the site, so it updates automatically when you change the source code. It's simply a list of directories that are (recursively I guess) watched by `mkdocs`.

Based on your directory structure, if you execute `mkdocs` in the `docs` directory, you should write:

```
    watch:
      - ../bot
```

If instead you are executing `mkdocs` in the root folder (with `-f docs/mkdocs.yml` option), you should write: 

```
    watch:
      - bot
```

See? It simply depends on "where" you are when you execute `mkdocs`.

Finally, for `pytkdocs` to be able to collect the documentation, your Python package must be available in the Python path. 

Here you get `ModuleNotFoundError: No module named 'bot'`, which means the import machinery cannot find your `bot` package.

If you run `mkdocs` while in the `docs` folder, it makes sense that Python cannot find the `bot` package since it one directory above.

So, again, depending on what directory you execute `mkdocs` into, you could try adding the `bot` parent directory to the PYTHONPATH:

```bash
# if you are into `docs`
PYTHONPATH=.. mkdocs serve
```

```bash
# if you are into the root folder and 'bot' is still not found
PYTHONPATH=. mkdocs serve
```

Hope this helps!

**Comment by dadyarri** [comment]
Thanks for a such fast reply.

About first one. It was inside the `mkdocstrings`, seems like it moved out while pasting to github

Hmm.. Added PYTHONPATH into a direnv config (tried also without it), now its crashes with
```python
TypeError: <module 'bot' (namespace)> is a built-in module
```

But, if i give bot  a some other name nothing changed

**Comment by pawamoy** [comment]
What crashes? Can you paste the complete traceback? What's the value of your PYTHONPATH? In what directory do you execute `mkdocs`?

**Comment by dadyarri** [comment]
- Only `mkdocstrings`
- Sure, sorry:
```
ERROR   -  mkdocstrings.handlers.python: Collection failed: <module 'bot' (namespace)> is a built-in module
Traceback (most recent call last):
  File "/home/dadyarri/projects/bjorn/venv_bjorn/lib/python3.8/site-packages/pytkdocs/cli.py", line 179, in main
    print(json.dumps(process_json(line)))
  File "/home/dadyarri/projects/bjorn/venv_bjorn/lib/python3.8/site-packages/pytkdocs/cli.py", line 116, in process_json
    return process_config(json.loads(json_input))
  File "/home/dadyarri/projects/bjorn/venv_bjorn/lib/python3.8/site-packages/pytkdocs/cli.py", line 98, in process_config
    serialized_obj = serialize_object(obj)
  File "/home/dadyarri/projects/bjorn/venv_bjorn/lib/python3.8/site-packages/pytkdocs/serializer.py", line 143, in serialize_object
    relative_file_path=obj.relative_file_path,
  File "/home/dadyarri/projects/bjorn/venv_bjorn/lib/python3.8/site-packages/pytkdocs/objects.py", line 185, in relative_file_path
    top_package_path = Path(inspect.getabsfile(top_package)).parent
  File "/usr/lib/python3.8/inspect.py", line 720, in getabsfile
    _filename = getsourcefile(object) or getfile(object)
  File "/usr/lib/python3.8/inspect.py", line 696, in getsourcefile
    filename = getfile(object)
  File "/usr/lib/python3.8/inspect.py", line 659, in getfile
    raise TypeError('{!r} is a built-in module'.format(object))
TypeError: <module 'bot' (namespace)> is a built-in module
```
- PYTHONPATH=..
- in `docs`

**Comment by pawamoy** [comment]
OK, it makes sense :slightly_smiling_face: 

Your bot package is in fact a namespace package since it has no `__init__.py` module. So `inspect.getabsfile` fails because it cannot find the `__init__.py` file. Not sure how I will fix this, but I'll try :smile:

**Comment by dadyarri** [comment]
OK, thank you a lot!

**Comment by pawamoy** [comment]
Open the relevant issue here: https://github.com/pawamoy/pytkdocs/issues/19

**Comment by chbndrhnns** [comment]
I see the issue is fixed in pytkdocs but the relevant release is not used for mkdocstrings. Would it be possible to bump the version here, too?

**Comment by pawamoy** [comment]
Done!
