### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by dadyarri** [pawamoy/mkdocstrings#81]
**Describe the bug**
`mkdocs build` (runned from directory with its config) raises this error
```
ERROR   -  Error reading page 'index.md': unsupported operand type(s) for +: 'NoneType' and 'str' 
Traceback (most recent call last):
  File "/home/dadyarri/projects/bjorn/venv_bjorn/bin/mkdocs", line 10, in <module>
    sys.exit(cli())
  File "/home/dadyarri/projects/bjorn/venv_bjorn/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/dadyarri/projects/bjorn/venv_bjorn/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/dadyarri/projects/bjorn/venv_bjorn/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dadyarri/projects/bjorn/venv_bjorn/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dadyarri/projects/bjorn/venv_bjorn/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/dadyarri/projects/bjorn/venv_bjorn/lib/python3.8/site-packages/mkdocs/__main__.py", line 159, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/home/dadyarri/projects/bjorn/venv_bjorn/lib/python3.8/site-packages/mkdocs/commands/build.py", line 274, in build
    _populate_page(file.page, config, files, dirty)
  File "/home/dadyarri/projects/bjorn/venv_bjorn/lib/python3.8/site-packages/mkdocs/commands/build.py", line 177, in _populate_page
    page.content = config['plugins'].run_event(
  File "/home/dadyarri/projects/bjorn/venv_bjorn/lib/python3.8/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "/home/dadyarri/projects/bjorn/venv_bjorn/lib/python3.8/site-packages/mkdocstrings/plugin.py", line 160, in on_page_content
    self.map_urls(page.canonical_url, item)
  File "/home/dadyarri/projects/bjorn/venv_bjorn/lib/python3.8/site-packages/mkdocstrings/plugin.py", line 173, in map_urls
    self.url_map[anchor.id] = base_url + anchor.url
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**index.md:**
```markdown
# Bjorn

[![MIT License](https://img.shields.io/pypi/l/aiogram.svg?style=flat-square)](https://opensource.org/licenses/MIT)
[![Telegram Bot API](https://img.shields.io/badge/Telegram%20Bot%20API-4.7-blue.svg?style=flat-square&logo=telegram)](https://core.telegram.org/bots/api)

Bot-helper for students groups written with [aiogram](https://aiogram.dev)

Docs for {{ version() }} [WIP]

## Функционал

- [Call](functions/call.md)
- [Mailings](functions/mailings.md)
- [Finances](functions/finances.md)
- [Schedule](functions/schedule.md)
- [Preferences](functions/preferences.md)
```

**Expected behavior**
No exception

**Information (please complete the following information):**
- OS: Manjaro linux
- Browser: Brave
- `mkdocstrings` 0.10.2

**Comment by thebigmunch** [comment]
This is a duplicate of #77.

**Comment by dadyarri** [comment]
Thanks, didn't see.
