### ISSUE TITLE
mkdocstrings and mkdocs-material seem incompatible

### ISSUE THREAD

**Issue by koaning** [pawamoy/mkdocstrings#84]
I wanted to release a new open source package today (over [here](https://github.com/RasaHQ/whatlies/)), but unfortunately find that I can no longer update the documentation. I see a lot of new version updates recently on pypi so I think that may be the reason why. 

**Describe the bug**

I am running python3.7 locally. With these versions installed; 

```
> python --version
Python 3.7.7
> python -m pip freeze | grep mkdocs
mkdocs==1.1
mkdocs-material==5.1.0
mkdocs-material-extensions==1.0b1
mkdocstrings==0.10.3
```

This is the `mkdocs.yml` file;

```
site_name: whatlies
extra_css: [style.css]
repo_url: https://github.com/RasaHQ/whatlies
site_url: https://rasahq.github.io/whatlies/
site_description: A python package to discover "what lies" in word embeddings.
site_author: Vincent D. Warmerdam @ Rasa Research

nav:
  - Home: index.md
  - Getting Started:
    - What Are Embeddings: tutorial/embeddings/index.md
    - Interactive Visualisation: tutorial/embeddingsets/index.md
    - Language Options: tutorial/languages/index.md
    - Transformation Viz: tutorial/transformations/index.md
  - API:
    - Embedding: api/embedding.md
    - EmbeddingSet: api/embeddingset.md
    - Transformers:
      - Pca: api/transformers/pca.md
      - Umap: api/transformers/umap.md
      - Noise: api/transformers/noise.md
      - Add Random: api/transformers/addrandom.md
    - Language:
        - spaCy: api/language/spacy_lang.md
        - Sense2Vec: api/language/s2v_lang.md
  - Roadmap: roadmap.md
plugins:
  - mkdocstrings
  - search
copyright: Copyright &copy; 2020 <a href="https://twitter.com/Rasa_HQ">Rasa</a>, Maintained by <a href="https://twitter.com/fishnets88">Vincent</a>.
theme:
  name: material
  custom_dir: theme/
  favicon: images/fig.png
  logo:
    icon: album
  feature:
    tabs: true
  palette:
    primary: white
    accent: purple
markdown_extensions:
  - toc:
      permalink: true
```

**To Reproduce**

```
> mkdocs serve
mkdocs serve                      
INFO    -  Building documentation... 
INFO    -  Cleaning site directory 
WARNING -  mkdocstrings.handlers.python: whatlies.embedding.Embedding: No type annotation for parameter 'name' 
WARNING -  mkdocstrings.handlers.python: whatlies.embedding.Embedding: No type annotation for parameter 'vector' 
WARNING -  mkdocstrings.handlers.python: whatlies.embedding.Embedding: No type annotation for parameter 'orig' 
WARNING -  mkdocstrings.handlers.python: whatlies.language.Sense2VecLangauge: No type annotation for parameter 'sense2vec_path' 
WARNING -  mkdocstrings.handlers.python: whatlies.language.Sense2VecLangauge.embset_similar: No type in return description 
WARNING -  mkdocstrings.handlers.python: whatlies.language.Sense2VecLangauge.score_similar: No type in return description 
WARNING -  mkdocstrings.handlers.python: whatlies.language.SpacyLanguage: No type annotation for parameter 'model_name' 
WARNING -  mkdocstrings.handlers.python: whatlies.transformers.addrandom.AddRandom: No type annotation for parameter 'n' 
WARNING -  mkdocstrings.handlers.python: whatlies.transformers.noise.Noise: No type annotation for parameter 'sigma' 
WARNING -  mkdocstrings.handlers.python: whatlies.transformers.noise.Noise: No type annotation for parameter 'seed' 
WARNING -  mkdocstrings.handlers.python: whatlies.transformers.pca.Pca: No type annotation for parameter 'n_components' 
WARNING -  mkdocstrings.handlers.python: whatlies.transformers.pca.Pca: No type annotation for parameter 'kwargs' 
WARNING -  mkdocstrings.handlers.python: whatlies.transformers.umap.Umap: No type annotation for parameter 'n_components' 
WARNING -  mkdocstrings.handlers.python: whatlies.transformers.umap.Umap: No type annotation for parameter 'kwargs' 
Traceback (most recent call last):
  File "/Users/vincent/Development/whatlies/venv/bin/mkdocs", line 10, in <module>
    sys.exit(cli())
  File "/Users/vincent/Development/whatlies/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/vincent/Development/whatlies/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/vincent/Development/whatlies/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/vincent/Development/whatlies/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/vincent/Development/whatlies/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/vincent/Development/whatlies/venv/lib/python3.7/site-packages/mkdocs/__main__.py", line 143, in serve_command
    **kwargs
  File "/Users/vincent/Development/whatlies/venv/lib/python3.7/site-packages/mkdocs/commands/serve.py", line 141, in serve
    config = builder()
  File "/Users/vincent/Development/whatlies/venv/lib/python3.7/site-packages/mkdocs/commands/serve.py", line 136, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/Users/vincent/Development/whatlies/venv/lib/python3.7/site-packages/mkdocs/commands/build.py", line 288, in build
    _build_theme_template(template, env, files, config, nav)
  File "/Users/vincent/Development/whatlies/venv/lib/python3.7/site-packages/mkdocs/commands/build.py", line 114, in _build_theme_template
    output = _build_template(template_name, template, files, config, nav)
  File "/Users/vincent/Development/whatlies/venv/lib/python3.7/site-packages/mkdocs/commands/build.py", line 93, in _build_template
    output = template.render(context)
  File "/Users/vincent/Development/whatlies/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/vincent/Development/whatlies/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/vincent/Development/whatlies/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/vincent/Development/whatlies/venv/lib/python3.7/site-packages/material/404.html", line 4, in top-level template code
    {% extends "base.html" %}
  File "/Users/vincent/Development/whatlies/venv/lib/python3.7/site-packages/material/base.html", line 108, in top-level template code
    {% block header %}
  File "/Users/vincent/Development/whatlies/venv/lib/python3.7/site-packages/material/base.html", line 109, in block "header"
    {% include "partials/header.html" %}
  File "/Users/vincent/Development/whatlies/venv/lib/python3.7/site-packages/material/partials/header.html", line 7, in top-level template code
    {% include "partials/logo.html" %}
  File "/Users/vincent/Development/whatlies/venv/lib/python3.7/site-packages/material/partials/logo.html", line 5, in top-level template code
    <img src="{{ config.theme.logo | url }}" alt="logo">
  File "/Users/vincent/Development/whatlies/venv/lib/python3.7/site-packages/mkdocs/utils/filters.py", line 14, in url_filter
    return normalize_url(value, page=context['page'], base=context['base_url'])
  File "/Users/vincent/Development/whatlies/venv/lib/python3.7/site-packages/mkdocs/utils/__init__.py", line 223, in normalize_url
    path = path_to_url(path or '.')
  File "/Users/vincent/Development/whatlies/venv/lib/python3.7/site-packages/mkdocs/utils/__init__.py", line 251, in path_to_url
    return '/'.join(path.split('\\'))
AttributeError: 'dict' object has no attribute 'split'
```

A few weeks ago it did work and I am trying to figure out what version of `mkdocstrings` was the one that worked for me. 

**Expected behavior**

No errors.

**Comment by koaning** [comment]
I can confirm there was a different bug in version 0.7.2. This error message appears when I install versions 0.8.0.

**Comment by koaning** [comment]
Found the culprit. It's not mkdocs or this package. It's mkdocs-material. This version seems to work just fine `mkdocs-material==4.6.3`. 

The material variant seems to be releasing [a lot recently](https://pypi.org/project/mkdocs-material/#history).

**Comment by pawamoy** [comment]
Hello, thank you very much for the detailed report, I appreciate it :slightly_smiling_face: 

So in the end it seems it has nothing to do with `mkdocstrings`? Did you open the issue on `mkdocs-material` instead?

**Comment by koaning** [comment]
I haven't yet, I was in a scramble this morning to get the docs working on my new project.

**Comment by pawamoy** [comment]
In https://github.com/pawamoy/mkdocstrings/issues/47#issuecomment-613434991 you mention it was related to #85. Could this issue be fixed as well by the solution in #85?

**Comment by pawamoy** [comment]
Related: https://github.com/mkdocs/mkdocs/issues/2052

**Comment by pawamoy** [comment]
I think you need to follow these instructions to upgrade to material 5: https://squidfunk.github.io/mkdocs-material/releases/5/

**Comment by pawamoy** [comment]
Can you report back if/when you get it to work? Thanks!

**Comment by pawamoy** [comment]
I'm pretty sure it was due to misconfiguration. Re-open if needed!
